services:
  web-provider:
    build:
      context: ..
      dockerfile: deploy/image/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../src:/app/bookstore
    ports:
      - "8000:8000"
    environment:
      POSTGRES_PASSWORD: 'Shekhar123#'
      POSTGRES_DB: 'opcua'
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST: 'host.docker.internal'
      POSTGRES_PORT: '5433'
    depends_on:
      # - db
      - redis
    restart: always
