services:
  web-bookstore:
    build:
      context: ..
      dockerfile: deploy/image/Dockerfile
      args:
        BUILD_NUMBER: ${BUILD_NUMBER}
    image: bookstore:${BUILD_NUMBER}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../src:/app/bookstore
    ports:
      - "8000:8000"
    environment:
      POSTGRES_PASSWORD: 'Shekhar123#'
      POSTGRES_DB: 'opcua'
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST: 'host.docker.internal'
      POSTGRES_PORT: '5433'
    restart: always
