# Generated by Django 5.1.1 on 2024-09-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcategory',
            name='board',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Board'),
        ),
    ]
