# Generated by Django 4.2.15 on 2024-09-11 11:52

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_legalcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcontent',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
