# Generated by Django 4.2.15 on 2024-09-11 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0009_order_phonepe_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhonePePaymentRequestDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="amount"
                    ),
                ),
                ("success", models.BooleanField(default=False, verbose_name="Success")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Code"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "merchant_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Merchant Transaction Id",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Transaction Id",
                    ),
                ),
                ("redirect_url", models.TextField(verbose_name="URL")),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="created at"),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.order",
                        verbose_name="Order id",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "PhonePePaymentRequestDetail",
                "verbose_name_plural": "PhonePePaymentRequestDetails",
            },
        ),
    ]
